services:
    # Huey scheduler - runs periodically to queue tasks via cron
    scheduler:
        image: openpodcast/connector-manager
        build:
            context: .
            dockerfile: Dockerfile
        command: ["/app/run_cron_scheduler.sh"]
        environment:
            - MYSQL_HOST=db
            - MYSQL_PORT=3306
            - MYSQL_USER=openpodcast
            - MYSQL_PASSWORD=openpodcast
            - MYSQL_DATABASE=openpodcast_auth
            - HUEY_DB_PATH=/app/data/huey.db
            # Reads from .env file if available
            - OPENPODCAST_ENCRYPTION_KEY=${OPENPODCAST_ENCRYPTION_KEY:-supersecret}
        env_file:
            - connector_manager/.env
        depends_on:
            - db
        volumes:
            - huey_data:/app/data

    # Huey worker - processes queued tasks
    worker:
        image: openpodcast/connector-manager
        build:
            context: .
            dockerfile: Dockerfile
        command: ["python", "/app/run_huey_consumer.py"]
        environment:
            - MYSQL_HOST=db
            - MYSQL_PORT=3306
            - MYSQL_USER=openpodcast
            - MYSQL_PASSWORD=openpodcast
            - MYSQL_DATABASE=openpodcast_auth
            - HUEY_DB_PATH=/app/data/huey.db
            - HUEY_WORKERS=4  # Number of worker processes
            # Reads from .env file if available
            - OPENPODCAST_ENCRYPTION_KEY=${OPENPODCAST_ENCRYPTION_KEY:-supersecret}
        env_file:
            - connector_manager/.env
        depends_on:
            - db
        volumes:
            - huey_data:/app/data
        # Can scale workers: docker-compose up --scale worker=3

    db:
        image: mysql:8.0
        volumes:
            - mysqldata:/var/lib/mysql
            - ./db_local_dev/schema.sql:/docker-entrypoint-initdb.d/00_schema.sql
        environment:
            MYSQL_DATABASE: openpodcast_auth
            MYSQL_USER: openpodcast
            MYSQL_ROOT_PASSWORD: openpodcast
            MYSQL_PASSWORD: openpodcast
        command: --innodb-buffer-pool-size=128M --innodb-buffer-pool-chunk-size=64M --key-buffer-size=5M --event-scheduler=ON

volumes:
    mysqldata:
    huey_data:
