CREATE DATABASE IF NOT EXISTS openpodcast;

CREATE TABLE IF NOT EXISTS openpodcast.podcasts (
  account_id INTEGER NOT NULL AUTO_INCREMENT,
  pod_name VARCHAR(2048) NOT NULL,
  PRIMARY KEY (account_id)
);

-- define access keys for podcast sources
CREATE TABLE IF NOT EXISTS podcastSources (
  account_id INTEGER NOT NULL,
  source_name ENUM('spotify','apple', 'anchor', 'podigee'),
  source_podcast_id VARCHAR(64) NOT NULL,
  -- keys are stored in json format and are encrypted by the client
  source_access_keys_encrypted JSON NOT NULL,
  PRIMARY KEY (account_id, source_name)
);

ALTER TABLE podcastSources
ADD CONSTRAINT podcastSources_account_id_fk
FOREIGN KEY (account_id) REFERENCES openpodcast.podcasts(account_id) ON DELETE CASCADE;

GRANT ALL PRIVILEGES ON openpodcast.* TO 'openpodcast'@'%';

INSERT INTO openpodcast.podcasts (account_id, pod_name)
VALUES
(1, 'podcast1'),
(2, 'podcast2'),
(3, 'podcast3');

-- "testvalue" encrypted using key "supersecret" abd base64 encoded is
-- "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ="
-- run will fail without proper data but executing of the manager can be tested
-- OPENPODCAST API Key for local API is: dummy-cn389ncoiwuencr
-- encoded with supersecret is: jA0ECQMIC/55CSVmUCP/0ksBnq5RMFcGYEf0Ie0rsnHB+SQoZNr7sm35nXlWruibLILn9qIg8fXaHPewqR6VMgXVWkrdZyx/UdwHBaHSXnCXTnnbwI8l1t/3SMs=

INSERT INTO podcastSources (account_id, source_name, source_podcast_id, source_access_keys_encrypted)
VALUES
-- (1, 'spotify', '1', '{"SPOTIFY_SP_DC": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ=", "SPOTIFY_SP_KEY": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ=", "SPOTIFY_PODCAST_ID": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ=", "OPENPODCAST_API_TOKEN": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ="}'),
-- (2, 'apple',  '1', '{"APPLE_AUTOMATION_ENDPOINT": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ=", "APPLE_AUTOMATION_BEARER_TOKEN": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ=", "APPLE_PODCAST_ID": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ=", "OPENPODCAST_API_TOKEN": "jA0EBwMCiwr1cCWJid//0j8B7rMbB+DT6lGsQpCerFKIeYNbe3YWcTKsvr+3fwAVwnJvxRbBAILR+9maT6rm56oC740ypydEHXQ7YVgyAIQ="}'),
-- (3, 'anchor', '1', '{"ANCHOR_WEBSTATION_ID": "jA0ECQMCd59Zr5Spp1P70joBVH4wA5Z51H0z8kTtM6/6L6V6kvfM1iqJNqnMWMpdoGx+eI3KvUL+o70Swqu8kTUA1vuq5yovkkNC", "ANCHOR_PW_S": "jA0ECQMCiq4eqyU0beD70owBXfQcj6xmBhOH1i+os6u0e4NDLVa6SFqCLyna++hyqmpMUVNoLIfrQWiasfIXIqNLMfn0A1bVG7+Pak9YfbK2mBu5V10+ka6jkI6hY+n40knOcro5QXmIhhfPyeYmNHrpYmVB7i9LPoxahRx0GGvatzkaSct22CquM/9Vw+mqiURShkAqoP2wkEjjDQ==", "OPENPODCAST_API_TOKEN": "jA0ECQMCHuVjSUBUvln70ksBKlRpJBvaLovudeM3wMvGvnZ8+mO3lejr0kT/ieb2AykHotJlOKGYPNQyXpy2cEWbG217AWy0pKhpTOQC225mcIJQlH7Ifj9yDW4=" }');
(1, 'anchor', 'fb37d7a4', '{"ANCHOR_WEBSTATION_ID": "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpqQTBFQ1FNSVZsRzZpSWt2ZDV2NzBqMEJSOThseE1BUDF2dy9QUFlTOGwvWjI5U3Y2WUZrMTduL0dMYnQ5eWRMCnhWbXEwd2Q0NlFRbVRkdDdYY2ExMXBvV3VTMUFsMTU2SDJ5UUtXVloKPWxIK2IKLS0tLS1FTkQgUEdQIE1FU1NBR0UtLS0tLQo=", "ANCHOR_PW_S": "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpqQTBFQ1FNSUhYOFZ3c3hleHZmNzBvVUJGcUR4MU5HemZBUm8zTkYzb1Y4SU1SVzZWeVBKRlpyUExTUlJMOW5pCisyRVdTNlYwQ1AxUXhtNVdjNDlzUTQrZFRXOWZWL2JZWkhwaUtKTmFSamZsVlB0cWtjMEJZejZMbmVtdVNzOS8KdmtzTGQraGQ4NTNWcDFtZjBwWVJRU25QZkJlZWhWT1NFY2RvYnZrT2lGZVNhUXBYKzlXNmFqTTF2WmR4MUxFbwpaUy9Panc2aAo9a1VidgotLS0tLUVORCBQR1AgTUVTU0FHRS0tLS0tCg==", "ANCHOR_BASE_URL": "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpqQTBFQ1FNSWJOSjlSamhBSXYvNzBtSUJSSThNOFA5d1gzNWl0VG1TeE5RUmxKRCtUOHBwSFNoQmhxekw1NVNaCktEMVNXTUs4c3M4RFY2bFh3UFFQT1QyTzBLOEMycnhpRTVXRzFSYnh5bjIyR2MzVmxzQ0FoTzA3YUFsNm43SmgKYUpVcHoyQjgvSHhWZTUyRmMvTzI0cnBpcXc9PQo9UzQrQgotLS0tLUVORCBQR1AgTUVTU0FHRS0tLS0tCg==", "ANCHOR_BASE_GRAPHQL_URL": "LS0tLS1CRUdJTiBQR1AgTUVTU0FHRS0tLS0tCgpqQTBFQ1FNSXNkbUR1UmhaUys3NzBtQUI5ZzNkWVREQ3J5WUpWSytkUXk5cWF1b1dKeUxqRFFvemhWRndnbjhvCmpiQzJPSXo2dmZ3TFRuT0NPaWtVRkhqdmRJRi9CSlQ3T3MwVi9VaE9jWHN1eHJwNTR6cTZSRVdESk4rYmxmMjEKZzAybm5wYU91MEc1K3BkRzN4c2dEbzg9Cj14YWZICi0tLS0tRU5EIFBHUCBNRVNTQUdFLS0tLS0K", "OPENPODCAST_API_TOKEN": "jA0ECQMIC/55CSVmUCP/0ksBnq5RMFcGYEf0Ie0rsnHB+SQoZNr7sm35nXlWruibLILn9qIg8fXaHPewqR6VMgXVWkrdZyx/UdwHBaHSXnCXTnnbwI8l1t/3SMs="}'),
(3, 'podigee', '51361', '{"PODIGEE_REFRESH_TOKEN": "jA0ECQMI3I//NAxLiRb60mEBwQFWoTv4KmXxPmoI4X5B8XEktOn4PZ0IM/CzsmgeOeKFV63DErompDF/hP9JBSkFRmJchxx7Y4tcuA7jfRw+A85k7u6ZmpRBnVo8TQbH0HISDQMECpzQVHO2cruGxmmT", "OPENPODCAST_API_TOKEN": "jA0ECQMIC/55CSVmUCP/0ksBnq5RMFcGYEf0Ie0rsnHB+SQoZNr7sm35nXlWruibLILn9qIg8fXaHPewqR6VMgXVWkrdZyx/UdwHBaHSXnCXTnnbwI8l1t/3SMs="}');